[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "minimalpackage"
dynamic = ["version", "dependencies"]
description = "Example of minimal package."
license = { text = "MIT" }
readme = "README.md"
requires-python = ">=3.9"
keywords = ["minimalpackage"]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
]

[[project.authors]]
name = "Gilberto Agostinho"
email = "gilbertohasnofb@gmail.com"

[project.optional-dependencies]
dev = [
    "setuptools==80.9.0",
]

[project.urls]
homepage = "https://github.com/gilbertohasnofb/minimalpackage"
source = "https://github.com/gilbertohasnofb/minimalpackage"

[tool.pytest.ini_options]
pythonpath = "src"
testpaths = "tests"

[tool.setuptools]
include-package-data = true
packages = ["minimalpackage"]
package-dir = { "" = "src" }

[tool.setuptools.package-data]
"*" = ["LICENSE", "README.md"]
"minimalpackage" = ["**/*"]

[tool.setuptools.dynamic]
version = {attr = "minimalpackage.__version__"}
dependencies = {file = ["requirements.txt"]}
