name: Commit Checker
on: [push]
jobs:
  test_code:
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        run: make setup
        
      - name: Unit tests
        run: make test
        
      - name: Check formatting
        run: make lint
